### ISSUE TITLE
Error unpacking binary Error: Could not find the End of Central Directory Record

### ISSUE THREAD

**Issue by igorsky78** [bubenshchykov/ngrok#103]
When I try to run npm install, the following error is thrown:

C:\Users\username\Documents\Visual Studio 2017\Projects\ProjectName\ProjectName.Web\ClientApp>npm install

> ngrok@0.1.98 postinstall C:\Users\username\Documents\Visual Studio 2017\Projects\ProjectName\ProjectName.Web\node_modules\ngrok
> node ./postinstall.js

ngrok - Downloading newest binary...
ngrok - Zipfile received (https://api.equinox.io/1/Applications/ap_pJSFC5wQYkAyI0FIVwKYs9h1hW/Updates/Asset/ngrok.zip?os=windows&arch=amd64&channel=stable) ...
Error: Could not find the End of Central Directory Record
    at DecompressZip.findEndOfDirectory (C:\Users\username\Documents\Visual Studio 2017\Projects\ProjectName\ProjectName.Web\node_modules\decompress-zip\lib\decompress-zip.js:165:15)
    at _fulfilled (C:\Users\username\Documents\Visual Studio 2017\Projects\ProjectName\ProjectName.Web\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\Users\username\Documents\Visual Studio 2017\Projects\ProjectName\ProjectName.Web\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\Users\username\Documents\Visual Studio 2017\Projects\ProjectName\ProjectName.Web\node_modules\q\q.js:816:13)
    at C:\Users\username\Documents\Visual Studio 2017\Projects\ProjectName\ProjectName.Web\node_modules\q\q.js:624:44
    at runSingle (C:\Users\username\Documents\Visual Studio 2017\Projects\ProjectName\ProjectName.Web\node_modules\q\q.js:137:13)
    at flush (C:\Users\username\Documents\Visual Studio 2017\Projects\ProjectName\ProjectName.Web\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by bubenshchykov** [comment]
hi, the module's version is too old (0.1.98), try latest 2.2.24 ;)

**Comment by bubenshchykov** [comment]
i guess everyth is fine, feel free to reopen if else :)
