### ISSUE TITLE
Something has broken 2.3.0

### ISSUE THREAD

**Issue by chaddjohnson** [bubenshchykov/ngrok#126]
Hi,

Thank you for the free software.

It appears a recent change broke an existing previous version. It is my understanding that changes should not break past versions.

When I run `yarn install` this happens now:

```
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/5] ⡀ parse-domain
[2/5] ⡀ phantomjs-prebuilt
[3/5] ⡀ fsevents
[4/5] ⡀ ngrok
error /Users/chad/development/projects/<redacted>/api/node_modules/ngrok: Command failed.
Exit code: 1
Command: node ./postinstall.js
Arguments: 
Directory: /Users/chad/development/projects/<redacted>/api/node_modules/ngrok
Output:
module.js:529
    throw err;
    ^

Error: Cannot find module 'json-stringify-safe'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chad/development/projects/<redacted>/api/node_modules/request/lib/helpers.js:3:25)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)




warning Error running install script for optional dependency: "/Users/chad/development/projects/<redacted>/api/node_modules/phantomjs-prebuilt: Command failed.\nExit code: 1\nCommand: node install.js\nArguments: \nDirectory: /Users/chad/development/projects/<redacted>/api/node_modules/phantomjs-prebuilt\nOutput:\nmodule.js:529\n    throw err;\n    ^\n\nError: Cannot find module 'json-stringify-safe'\n    at Function.Module._resolveFilename (module.js:527:15)\n    at Function.Module._load (module.js:476:23)\n    at Module.require (module.js:568:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/Users/chad/development/projects/<redacted>/api/node_modules/request/lib/helpers.js:3:25)\n    at Module._compile (module.js:624:30)\n    at Object.Module._extensions..js (module.js:635:10)\n    at Module.load (module.js:545:32)\n    at tryModuleLoad (module.js:508:12)\n    at Function.Module._load (module.js:500:3)"
info This module is OPTIONAL, you can safely ignore this error
```

Any idea what happened, and can this be fixed? This is very frustrating as I cannot start my app now.

**Comment by chaddjohnson** [comment]
Fixed by upgrading to the latest version.

I was avoiding upgrading because it was freezing when I ran my app, but I was promisifying `ngrok.connect()`, and since v3 appears to use promises, this is no longer necessary.
