### ISSUE TITLE
ngrok@3.1.1 unable to install!

### ISSUE THREAD

**Issue by amandeepmittal** [bubenshchykov/ngrok#140]
Here is the complete error with the screenshot.

```
usr/local/bin/ngrok -> /usr/local/lib/node_modules/ngrok/bin/ngrok

> ngrok@3.1.1 postinstall /usr/local/lib/node_modules/ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip
ngrok - downloading progress: 14864759/14864759
ngrok - binary downloaded to /Users/amanhimself/.ngrok/aHR0cHM6Ly9iaW4uZXF1aW5veC5pby9jLzRWbUR6QTdpYUhiL25ncm9rLXN0YWJsZS1kYXJ3aW4tYW1kNjQuemlw.zip
ngrok - unpacking binary
ngrok - error unpacking binary { [Error: EACCES: permission denied, open '/usr/local/lib/node_modules/ngrok/bin/ngrok']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/ngrok/bin/ngrok' }
ngrok - install failed, retrying
ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip
ngrok - downloading progress: 14864759/14864759
ngrok - binary downloaded to /Users/amanhimself/.ngrok/aHR0cHM6Ly9iaW4uZXF1aW5veC5pby9jLzRWbUR6QTdpYUhiL25ncm9rLXN0YWJsZS1kYXJ3aW4tYW1kNjQuemlw.zip
ngrok - unpacking binary
ngrok - error unpacking binary { [Error: EACCES: permission denied, open '/usr/local/lib/node_modules/ngrok/bin/ngrok']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/ngrok/bin/ngrok' }
ngrok - install failed, retrying
ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip
ngrok - downloading progress: 14864759/14864759
ngrok - binary downloaded to /Users/amanhimself/.ngrok/aHR0cHM6Ly9iaW4uZXF1aW5veC5pby9jLzRWbUR6QTdpYUhiL25ncm9rLXN0YWJsZS1kYXJ3aW4tYW1kNjQuemlw.zip
ngrok - unpacking binary
ngrok - error unpacking binary { [Error: EACCES: permission denied, open '/usr/local/lib/node_modules/ngrok/bin/ngrok']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/ngrok/bin/ngrok' }
ngrok - install failed { [Error: EACCES: permission denied, open '/usr/local/lib/node_modules/ngrok/bin/ngrok']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/ngrok/bin/ngrok' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngrok@3.1.1 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ngrok@3.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/amanhimself/.npm/_logs/2019-03-10T18_49_36_973Z-debug.log
```

![Screenshot 2019-03-11 at 12 22 52 AM](https://user-images.githubusercontent.com/10234615/54089902-15b64b80-4394-11e9-8132-fe74fdebe63b.png)

**Comment by rodrigocam** [comment]
This one did the trick for me:

```
sudo npm i -g ngrok --unsafe-perm=true --allow-root
```

**Comment by OZZlE** [comment]
remove `sudo` and it works even better

     npm i -g ngrok --unsafe-perm=true --allow-root

See: https://github.com/bubenshchykov/ngrok/issues/87

**Comment by akshayuppal3** [comment]
still facing the same issue. It didn't resolve.

```
ngrok - downloading binary https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-arm64.zip
ngrok - downloading progress:
ngrok - error downloading from URL RequestError: Hostname/IP does not match certificate's altnames: Host: bin.equinox.io. is not in the cert's altnames: DNS:c.sni-561-default.ssl.fastly.net
    at ClientRequest.<anonymous> (/opt/homebrew/lib/node_modules/ngrok/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/opt/homebrew/lib/node_modules/ngrok/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at new NodeError (internal/errors.js:322:7)
    at Object.checkServerIdentity (tls.js:347:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1525:27)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12) {
  code: 'ERR_TLS_CERT_ALTNAME_INVALID',
  timings: {
    start: 1693509259197,
    socket: 1693509259197,
    lookup: 1693509264205,
    connect: 1693509264217,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1693509264254,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 5008,
      tcp: 12,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 5057
    }
  }
}
ngrok - install failed RequestError: Hostname/IP does not match certificate's altnames: Host: bin.equinox.io. is not in the cert's altnames: DNS:c.sni-561-default.ssl.fastly.net
    at ClientRequest.<anonymous> (/opt/homebrew/lib/node_modules/ngrok/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/opt/homebrew/lib/node_modules/ngrok/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at new NodeError (internal/errors.js:322:7)
    at Object.checkServerIdentity (tls.js:347:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1525:27)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12) {
  code: 'ERR_TLS_CERT_ALTNAME_INVALID',
  timings: {
    start: 1693509259197,
    socket: 1693509259197,
    lookup: 1693509264205,
    connect: 1693509264217,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1693509264254,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 5008,
      tcp: 12,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 5057
    }
  }
}
```
