### ISSUE TITLE
ngrok not working on docker alpine images anymore

### ISSUE THREAD

**Issue by szanata** [bubenshchykov/ngrok#141]
Hi there! I'm having some problems here, before update `3.1.1` I was able to run ngrok inside a docker container using alpine and slim node images, after the last release it start throwing this error:

```bash
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./ngrok ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:777:11)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

Is this expected?

On stretch images it works fine.

Thank you very much

**Comment by bubenshchykov** [comment]
Hi! Thanks for reporting, that's not expected
Is it specifically 3.1.1 that breaks it - does 3.1.0 runs fine on alpine/slim ?

**Comment by szanata** [comment]
Hi @bubenshchykov, thanks for responding! The previous version we were using was 3.0.1, that worked for sure. I'll test the 3.1.0 today and I'll reply to you.

**Comment by szanata** [comment]
Hi @bubenshchykov, I took some time re-tested everything and here what I found out:

For starters, the lib is not working in alpine images, event the v3.0.1. I'm pretty sure this is related to the binary, but here is a chart of were I could make it run properly:

| ngrok | node:8.10-alpine | node:11.6-apline | node:8.10-slim | node:11.6-slim | node:8.10-stretch | node:11.6-stretch |
| - | - | - | - | - | - | - |
| 3.0.1 | no | no | yes | yes | yes | yes | yes |
| 3.1.0 | no | no | yes | yes | yes | yes | yes |
| 3.1.1 | no | no | yes | yes | yes | yes | yes |

Saying that I'm sure it worked before on alpine images, as we have a project with ngrok in production for almost a year now, and it start breaking about 20 days ago or so.

Diving further I discover the errors are always the same on all node 8 images, and are also the same on all node 11 images:

**node 8 error**
```bash
Error: spawn ./ngrok ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:1
```

**node 11 error**
```bash
Error: spawn ./ngrok ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:777:11)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

Saying that, I tempered with the node `spawn` to get more details and this is what I got:

I set this event listener to the `spawn`:
```js
ngrok.on('error', err => {
  console.log( 'on error', err );
});
```

And got this error:

```bash
on error { Error: spawn ./ngrok ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:777:11)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ./ngrok',
  path: './ngrok',
  spawnargs: [ 'start', '--none', '--log=stdout' ] }
```

Also, no matter which node/image version, the arguments used on `spaw` have always the same value:

```js
{ bin: './ngrok', start: '[ 'start', '--none', '--log=stdout' ]', dir: '/app/node_modules/ngrok/bin' }
```

Finally, I decided to invoke the ngrok binary manually inside the docker images, and it worked flawless on slim and stretch images, but on alpine images it threw and error:

```bash
/app # source ./node_modules/ngrok/bin/ngrok 
/bin/sh: ./node_modules/ngrok/bin/ngrok: line 1: can't create ??E@p@8: Illegal byte sequence
/bin/sh: ./node_modules/ngrok/bin/ngrok: line 1: ELF: not found
/bin/sh: ./node_modules/ngrok/bin/ngrok: ?: not found
/bin/sh: ./node_modules/ngrok/bin/ngrok: line 2: @%: not found
/bin/sh: ./node_modules/ngrok/bin/ngrok: line 3: ,?: not found
/bin/sh: ./node_modules/ngrok/bin/ngrok: line 4: ?P: not found
/bin/sh: ./node_modules/ngrok/bin/ngrok: line 5:????o?: not found
/bin/sh: ./node_modules/ngrok/bin/ngrok: line 6: ,?: not found
/bin/sh: ./node_modules/ngrok/bin/ngrok: line 7: ?Z
                                                   ?@
                                                     ,@
                                                       ??
                                                        ?: not found
/bin/sh: ./node_modules/ngrok/bin/ngrok: line 10: syntax error: unexpected ")"
```

And, just to make sure, no matter if I'm installing on stretch, alpine or slim, it always downloaded the same binary, the url is: *https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip*.

Hope this is helpful to you, thanks!

**Comment by balaabhinav** [comment]
I am facing the same issue. Any updates on this ?

**Comment by Mickael-van-der-Beek** [comment]
I encountered the same issue and managed to fix it.

During the NPM install phase, the binary that is downloaded by `ngrok` depends on the result of the calls `os.platform()` and `os.arch()` [1]. For Alpine Linux that value is `linuxx64` [2].

Now if you change it to the `linuxia32` build, it works again.

One way to achieve this result without modifying the code of `ngrok` is to pass the following ENV variable: `NGROK_ARCH=linuxia32`.

I'm guessing that the issue might be related with the `ngrok` binary being compiled with `libc` and Alpine Linux using `muslc`. Not sure why the `linuxia32` (`linux-386` on the CDN) build works though.

[1] https://github.com/bubenshchykov/ngrok/blob/b078b1b0c27ee30d93250b52d88e0a6ac3a38d24/postinstall.js#L28
[2]: https://github.com/bubenshchykov/ngrok/blob/b078b1b0c27ee30d93250b52d88e0a6ac3a38d24/postinstall.js#L32,L41

**Comment by bubenshchykov** [comment]
hi guys! @szanata thank you very much for putting all the details together
unfortunately, I won't be able to work on it nearest weeks
so if anyone can take a lead on this issue - that would be great!

alternatively, you can manually download the binary in your docker image
https://ngrok.com/download

you can also call the ngrok directly, outside node, of course

**Comment by barronwei** [comment]
Has there been fix for this issue? Adding the environment variable `NGROK_ARCH` per @Mickael-van-der-Beek on version `3.2.4` did not work for me.

**Comment by parithon** [comment]
@barronwei For me the following works for me:

```
FROM node:12.6.0-alpine
...
RUN export NGROK_ARCH=linuxia32 \
    && npm run ci --silent --only=production
```
