### ISSUE TITLE
error code ELIFECYCLE

### ISSUE THREAD

**Issue by arunpkumar92** [bubenshchykov/ngrok#200]
2113 error code ELIFECYCLE
2114 error errno 1
2115 error ngrok@3.3.0 postinstall: `node ./postinstall.js`
2115 error Exit status 1
2116 error Failed at the ngrok@3.3.0 postinstall script.
2116 error This is probably not a problem with npm. There is likely additional logging output above.
2117 verbose exit [ 1, true ]

**Comment by philnash** [comment]
Hi @arunpkumar92, thanks for this report. Could you give a few more details please? To start, what operating system are you running this on? Also, what Node version? And was there any other relevant logs in the output from before this error?

**Comment by arunpkumar92** [comment]
OS -  Catalina
node - v12.13.1

**Comment by philnash** [comment]
Thanks for those bits, can you also let me know whether there were any other logs in the output from before the error?

**Comment by SonsofKings** [comment]
Doesn't look like there's been any updates on this issue but I started getting this myself. Is it ok if I bump with included logs?

```
root@raspberrypi:/home/pi/nrlx# npm i ngrok

> ngrok@4.3.1 postinstall /home/pi/nrlx/node_modules/ngrok
> node ./postinstall.js

internal/util.js:214
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:214:11)
    at Object.<anonymous> (/home/pi/nrlx/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at downloadNgrok (/home/pi/nrlx/node_modules/ngrok/download.js:14:23)
npm WARN node-fetch@2.6.7 requires a peer of encoding@^0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nrlx/framework@1.0.0 No description
npm WARN @nrlx/framework@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngrok@4.3.1 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngrok@4.3.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-06T17_09_18_462Z-debug.log

```

**Comment by philnash** [comment]
Thanks for the logs @SonsofKings. What version of Node.js are you installing this with?

**Comment by SonsofKings** [comment]
hey @philnash thanks for getting back to me, I'm running node 16.14.0

**Comment by philnash** [comment]
Huh, that's not it then.

The error you are getting says that it happened on [line 14 of download.js](https://github.com/bubenshchykov/ngrok/blob/master/download.js#L14) which is where `extract-zip` is required.

Can you try to `npm install extract-zip` and just run a simple test where you require it (even in the REPL) on your raspberry pi and see what happens?

**Comment by philnash** [comment]
Hi @SonsofKings, were you able to look further into this?
