### ISSUE TITLE
install fails with self-signed cert

### ISSUE THREAD

**Issue by rscottfree** [bubenshchykov/ngrok#21]
I'm behind a corporate proxy that rewrites SSL certs, and the post install script that downloads the ngrok zip file fails with a self-signed cert error. Can we change this list of URLs to use http instead of https?

I don't use ngrok directly, but the latest RC of the browser-sync npm package has a dependency on it, and the browser-sync install fails because of of this self-signed cert error with ngrok.

The error I get:
> node ./postinstall.js

ngrok - Downloading newest binary...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: SELF_SIGNED_CERT_IN_CHAIN
    at SecurePair.<anonymous> (tls.js:1381:32)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10)
    at CleartextStream.read [as _read] (tls.js:472:13)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
npm ERR! ngrok@0.1.98 postinstall: `node ./postinstall.js`

**Comment by bubenshchykov** [comment]
Sad to hear that - I'll look into it and let you know

**Comment by bubenshchykov** [comment]
@rscottfree i can't use http because of security concerns
I suggest u either create a small http fork of ngrok and use it in browser-sync

or

we can support ngrok options in package.json of consumers, eg 
```javascript
{
     dependencies: {..},
     ngrok: {
           http: true, // or better some ssl-related options which will make it work
     }
}```

**Comment by rscottfree** [comment]
@bubenshchykov I understand the security concerns. For now it's working to just use a fork where I have set everything to http. Thanks for looking into it.
