### ISSUE TITLE
Error downloading binaries on circleci

### ISSUE THREAD

**Issue by mjog** [bubenshchykov/ngrok#238]
Not sure if this is a error here or in `got`, but I'm recently seeing these when installing ngrok in it's postinstall for a project on Circle CI:

```
> ngrok@4.0.1 postinstall /home/circleci/repo/node_modules/ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
ngrok - downloading progress: (node:163) ExperimentalWarning: The dns.promises API is experimental
(node:163) ExperimentalWarning: The http2 module is an experimental API.

ngrok - error downloading from URL { RequestError: The "listener" argument must be of type Function. Received type object
    at Request._makeRequest (/home/circleci/repo/node_modules/got/dist/source/core/index.js:1177:19)
    at Request (/home/circleci/repo/node_modules/got/dist/source/core/index.js:328:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:236:19)
    at ClientRequest.once (events.js:288:11)
    at new ClientRequest (_http_client.js:141:10)
    at request (https.js:272:10)
    at Request._makeRequest (/home/circleci/repo/node_modules/got/dist/source/core/index.js:1124:43)
    at Request (/home/circleci/repo/node_modules/got/dist/source/core/index.js:328:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)
  name: 'RequestError',
  code: 'ERR_INVALID_ARG_TYPE',
  timings: undefined }
ngrok - install failed, retrying
ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
ngrok - downloading progress: 
ngrok - error downloading from URL { RequestError: The "listener" argument must be of type Function. Received type object
    at Request._makeRequest (/home/circleci/repo/node_modules/got/dist/source/core/index.js:1177:19)
    at Request (/home/circleci/repo/node_modules/got/dist/source/core/index.js:328:28)
    at ClientRequest.once (events.js:288:11)
    at new ClientRequest (_http_client.js:141:10)
    at request (https.js:272:10)
    at Request._makeRequest (/home/circleci/repo/node_modules/got/dist/source/core/index.js:1124:43)
    at Request (/home/circleci/repo/node_modules/got/dist/source/core/index.js:328:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'RequestError',
  code: 'ERR_INVALID_ARG_TYPE',
  timings: undefined }
ngrok - install failed, retrying
ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
ngrok - downloading progress: 
ngrok - error downloading from URL { RequestError: The "listener" argument must be of type Function. Received type object
    at Request._makeRequest (/home/circleci/repo/node_modules/got/dist/source/core/index.js:1177:19)
    at Request (/home/circleci/repo/node_modules/got/dist/source/core/index.js:328:28)
    at ClientRequest.once (events.js:288:11)
    at new ClientRequest (_http_client.js:141:10)
    at request (https.js:272:10)
    at Request._makeRequest (/home/circleci/repo/node_modules/got/dist/source/core/index.js:1124:43)
    at Request (/home/circleci/repo/node_modules/got/dist/source/core/index.js:328:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'RequestError',
  code: 'ERR_INVALID_ARG_TYPE',
  timings: undefined }
ngrok - install failed { RequestError: The "listener" argument must be of type Function. Received type object
    at Request._makeRequest (/home/circleci/repo/node_modules/got/dist/source/core/index.js:1177:19)
    at Request (/home/circleci/repo/node_modules/got/dist/source/core/index.js:328:28)
    at ClientRequest.once (events.js:288:11)
    at new ClientRequest (_http_client.js:141:10)
    at request (https.js:272:10)
    at Request._makeRequest (/home/circleci/repo/node_modules/got/dist/source/core/index.js:1124:43)
    at Request (/home/circleci/repo/node_modules/got/dist/source/core/index.js:328:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'RequestError',
  code: 'ERR_INVALID_ARG_TYPE',
  timings: undefined }
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngrok@4.0.1 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngrok@4.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2021-07-25T23_30_51_297Z-debug.log
```

**Comment by philnash** [comment]
That's a new one. What version of Node is this happening on?

**Comment by mjog** [comment]
Ah! Thank you for that question - turns out the CCI config handn't been updated and was still using Node 10.

**Comment by philnash** [comment]
Oh, that's not what I expected! But glad it's solved!
