### ISSUE TITLE
How to fix TypeError: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by yasminlopestestes** [bubenshchykov/ngrok#309]
```
TypeError: Cannot read property 'body' of undefined
    at NgrokClient.request (C:\Users\progweb\Documents\Projetos\cucaweb-node\node_modules\ngrok\src\client.js:40:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async connectRetry (C:\Users\progweb\Documents\Projetos\cucaweb-node\node_modules\ngrok\index.js:29:22)
```

**Comment by mschultz-kaliop** [comment]
Upgrading to v5.0.0-beta.2 works for me, thanks @xavierhamel !
