### ISSUE TITLE
Post install script is failing (sometimes) for v0.1.x

### ISSUE THREAD

**Issue by shavo007** [bubenshchykov/ngrok#39]
Error when I run  npm install grunt-psi --save-dev on windows 8.

```
> ngrok@0.1.99 postinstall c:\java-projects\track-ui\node_modules\grunt-psi\node_modules\ngrok
> node ./postinstall.js

ngrok - downloading newest binary...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-psi" "--save-dev"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! ngrok@0.1.99 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ngrok@0.1.99 postinstall script 'node ./postinstall.js'.
```

Is this a proxy issue or an issue with the module?

Regards,
Shane.

**Comment by bubenshchykov** [comment]
Hi, I saw two similar issues - one because of some corporate proxies and second most popular is because of bins hosting instability. Are you still unable to install it?

**Comment by shavo007** [comment]
Hi.

I move to a mac so I cant say!! Windows was just a pain for installing many node modules.

**Comment by bubenshchykov** [comment]
good choice :)
