### ISSUE TITLE
Error unpacking binary Error: Could not find the End of Central Directory Record

### ISSUE THREAD

**Issue by jcarpe** [bubenshchykov/ngrok#69]
When I try to install ngrok (`npm i -g ngrok`), the following error is thrown:
```
ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip ...
ngrok - binary downloaded...
ngrok - error unpacking binary Error: Could not find the End of Central Directory Record
    at DecompressZip.findEndOfDirectory (/Users/jcarpe/.nvm/versions/node/v6.9.4/lib/node_modules/ngrok/node_modules/decompress-zip/lib/decompress-zip.js:165:15)
    at _fulfilled (/Users/jcarpe/.nvm/versions/node/v6.9.4/lib/node_modules/ngrok/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/jcarpe/.nvm/versions/node/v6.9.4/lib/node_modules/ngrok/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/jcarpe/.nvm/versions/node/v6.9.4/lib/node_modules/ngrok/node_modules/q/q.js:796:13)
    at /Users/jcarpe/.nvm/versions/node/v6.9.4/lib/node_modules/ngrok/node_modules/q/q.js:604:44
    at runSingle (/Users/jcarpe/.nvm/versions/node/v6.9.4/lib/node_modules/ngrok/node_modules/q/q.js:137:13)
    at flush (/Users/jcarpe/.nvm/versions/node/v6.9.4/lib/node_modules/ngrok/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
This leads me to believe the the file that is downloaded to be unpacked is corrupt or it had not actually completed download prior to unpacking?

Node: v6.9.4
Npm: v4.0.5

**Comment by jcarpe** [comment]
Actually, when I lock the npm version at 2.2.4 (as oppossed to ^2.2.4), everything installs fine.

**Comment by mica16** [comment]
Hi,
Any solutions on this ?
bin.equinox.io bin.equinox.io seems to be down ?

```
ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip ...
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: getaddrinfo ENOTFOUND bin.equinox.io bin.equinox.io:443
```

**Comment by bubenshchykov** [comment]
@inconshreveable hi! :)
was is it a temporary equinox glitch?

**Comment by inconshreveable** [comment]
hiya! yeah looks like it was just a temporary failure of some sort:

```
inconshreveable [~] ♡ : curl https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip > ngrok.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5008k  100 5008k    0     0   155k      0  0:00:32  0:00:32 --:--:--  176k

inconshreveable [~] ♡ : unzip ngrok.zip 
Archive:  ngrok.zip
  inflating: ngrok                   

inconshreveable [~] ♡ : ./ngrok 
NAME:
   ngrok - tunnel local ports to public URLs and inspect traffic
```

**Comment by bubenshchykov** [comment]
works fine for me too
```
$ npm i ngrok -g
/usr/local/bin/ngrok -> /usr/local/lib/node_modules/ngrok/bin/ngrok

> ngrok@2.2.6 postinstall /usr/local/lib/node_modules/ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip ...
ngrok - binary downloaded...
ngrok - binary unpacked.
```

**Comment by chee** [comment]
this is happening to me now. the url it's trying to hit is https://api.equinox.io/1/Applications/ap_pJSFC5wQYkAyI0FIVwKYs9h1hW/Updates/Asset/ngrok.zip?channel=stable&os=linux&arch=amd64 , which gives me a 401

**Comment by bubenshchykov** [comment]
Hi, try latest version. The link should start with
https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-..
https://github.com/bubenshchykov/ngrok/blob/master/postinstall.js#L6


ср, 22 бер. 2017 о 06:55 chee <notifications@github.com> пише:

**Comment by mayacode** [comment]
So I experience it now... any hint?

```error /Users/mm/projects/alfa/frontend/node_modules/ngrok: Command failed.
Exit code: 1
Command: node ./postinstall.js
Arguments:
Directory: /Users/mm/projects/alfa/frontend/node_modules/ngrok
Output:
ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip ...
ngrok - binary downloaded...
ngrok - error unpacking binary Error: Could not find the End of Central Directory Record
    at DecompressZip.findEndOfDirectory (/Users/mm/projects/alfa/frontend/node_modules/decompress-zip/lib/decompress-zip.js:165:15)
    at _fulfilled (/Users/mm/projects/alfa/frontend/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/mm/projects/alfa/frontend/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/mm/projects/alfa/frontend/node_modules/q/q.js:816:13)
    at /Users/mm/projects/alfa/frontend/node_modules/q/q.js:624:44
    at runSingle (/Users/mm/projects/alfa/frontend/node_modules/q/q.js:137:13)```

**Comment by bubenshchykov** [comment]
Looks like equinox hosting issue. As a quick solution, you can host ngrok
binary yourself and set NGROK_CDN_URL env var before npm install. I will
look into issue later today too
